In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn import datasets

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

from sklearn.neural_network import MLPClassifier
diabetes = datasets.load_diabetes()

df = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)

df["diabetes"] = diabetes.target

df.head()
df.describe().transpose()


count          mean        std  ...         50%         75%         max
age       442.0 -3.634285e-16   0.047619  ...    0.005383    0.038076    0.110727
sex       442.0  1.308343e-16   0.047619  ...   -0.044642    0.050680    0.050680
bmi       442.0 -8.045349e-16   0.047619  ...   -0.007284    0.031248    0.170555
bp        442.0  1.281655e-16   0.047619  ...   -0.005671    0.035644    0.132044
s1        442.0 -8.835316e-17   0.047619  ...   -0.004321    0.028358    0.153914
s2        442.0  1.327024e-16   0.047619  ...   -0.003819    0.029844    0.198788
s3        442.0 -4.574646e-16   0.047619  ...   -0.006584    0.029312    0.181179
s4        442.0  3.777301e-16   0.047619  ...   -0.002592    0.034309    0.185234
s5        442.0 -3.830854e-16   0.047619  ...   -0.001948    0.032433    0.133599
s6        442.0 -3.412882e-16   0.047619  ...   -0.001078    0.027917    0.135612
diabetes  442.0  1.521335e+02  77.093005  ...  140.500000  211.500000  346.000000

[11 rows x 8 columns]

In [ ]:




target_column = ['diabetes'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))





(309, 10)
(133, 10)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

        25.0       0.00      0.00      0.00         1
        31.0       0.00      0.00      0.00         1
        37.0       0.50      1.00      0.67         1
        39.0       0.00      0.00      0.00         2
        42.0       0.00      0.00      0.00         3
        44.0       0.00      0.00      0.00         1
        45.0       0.33      1.00      0.50         1
        47.0       0.00      0.00      0.00         2
        48.0       0.00      0.00      0.00         3
        49.0       0.00      0.00      0.00         2
        50.0       0.00      0.00      0.00         1
        51.0       0.00      0.00      0.00         3
        53.0       0.50      0.33      0.40         3
        54.0       0.00      0.00      0.00         1
        55.0       0.00      0.00      0.00         3
        57.0   

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and